### ISSUE TITLE
Error 500 - unable to open database file

### ISSUE THREAD

**Issue by pawel-czernecki** [bramanda48/docker-mailserver-webapi#13]
Hi, I've encountered an issue while using your project

When I tried execute

docker exec -ti mailserver curl -X 'GET'   'http://localhost:3000/api/v1/email'   -H 'accept: */*'   -H 'X-API-Key: xxxxxxxxxxxxxxxxxx'

then I get the following response:

{"statusCode":500,"metadata":{"request":{"timestamp":"2024-04-22T08:58:08.469Z","method":"GET","path":"/api/v1/email"},"pagination":null},"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"14: unable to open database file","stack":"Error: 14: unable to open database file\n    at Yc (file:///tmp/docker-mailserver/webapi/main.esm.js:52:14126)\n    at s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:4084)\n    at eventLoopTick (ext:core/01_core.js:168:7)\n    at async file:///tmp/docker-mailserver/webapi/main.esm.js:60:4980\n    at async s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:3993)\n    at async file:///tmp/docker-mailserver/webapi/main.esm.js:60:5325\n    at async s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:3993)\n    at async file:///tmp/docker-mailserver/webapi/main.esm.js:35:20313\n    at async s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:3993)\n    at async file:///tmp/docker-mailserver/webapi/main.esm.js:35:20196"}],"data":null}

I used the installation script from the readme, and these are my environment variables:

WEB_API_FAIL2BAN_SQLITE_PATH="/var/lib/fail2ban/fail2ban.sqlite3"
WEB_API_KEY="xxxxxxxxxxxx"
WEB_API_WHITELISTED_IP="xx.xx.xx.xx,127.0.0.1,172.23.0.1"
DENO_ENV="production"
WEB_API_DMS_CONFIG_PATH="/tmp/docker-mailserver"

And there are a files with permissions using by your api:

-rwxrwxrwx 1 root root    0 Apr 22 08:06 dovecot-masters.cf
-rwxrwxrwx 1 root root    0 Mar 25 13:00 dovecot-quotas.cf
drwxr-xr-x 3 root root 4096 Mar 25 13:23 opendkim
-rwxrwxrwx 1 root root 2142 Apr 22 08:06 postfix-accounts.cf
-rwxrwxrwx 1 root root   47 Apr  4 09:55 postfix-main.cf
-rwxrwxrwx 1 root root    0 Apr 16 21:47 postfix-receive-access.cf
-rwxrwxrwx 1 root root    0 Apr 16 21:47 postfix-relaymap.cf
-rwxrwxrwx 1 root root    0 Apr 16 21:47 postfix-sasl-password.cf
-rwxrwxrwx 1 root root    0 Apr 16 21:47 postfix-send-access.cf
-rwxrwxrwx 1 root root    0 Apr 16 21:47 postfix-virtual.cf

I've given them full permissions, but it hasn't helped.

Could you help me to resolve this issue?

**Comment by bramanda48** [comment]
Hi, thanks for letting me know about this issue.

> {"statusCode":500,"metadata":{"request":{"timestamp":"2024-04-22T08:58:08.469Z","method":"GET","path":"/api/v1/email"},"pagination":null},"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"14: unable to open database file","stack":"Error: 14: unable to open database file\n at Yc (file:///tmp/docker-mailserver/webapi/main.esm.js:52:14126)\n at s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:4084)\n at eventLoopTick (ext:core/01_core.js:168:7)\n at async file:///tmp/docker-mailserver/webapi/main.esm.js:60:4980\n at async s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:3993)\n at async file:///tmp/docker-mailserver/webapi/main.esm.js:60:5325\n at async s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:3993)\n at async file:///tmp/docker-mailserver/webapi/main.esm.js:35:20313\n at async s (file:///tmp/docker-mailserver/webapi/main.esm.js:35:3993)\n at async file:///tmp/docker-mailserver/webapi/main.esm.js:35:20196"}],"data":null}

This error occurs because the application can't find the Fail2Ban database, and the `ENABLE_FAIL2BAN` setting is inactive.(https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#enable_fail2ban). 

To resolve, you can turn on `ENABLE_FAIL2BAN` in the DMS configuration or just rebuild the container because I've added some checks in the latest script.
